config:
  export_path: /home/ace/migration
  export_type: patient
  file_map_location: lib/migrator
  start_date: "2011-01-01"
  end_date: "2011-01-31 23:59:59"
  encounter_type_to_export: 0
  encounters_list: ""
  limit: 0
